### ISSUE TITLE
 Plone 4.3.19 build error

### ISSUE THREAD

**Issue by zhou0** [collective/collective.documentgenerator#32]
Version and requirements information containing future:
  [versions] constraint on future: 0.13.1
  Requirement of collective.documentgenerator: future>=0.14.0
  Requirement of z3c.table: future>=0.14.0
While:
  Installing instance.
Error: The requirement ('future>=0.14.0') is not allowed by your [versions] constraint (0.13.1)
[lzhou@localhost zinstance]$ bin/buildout
Installing instance.
Version and requirements information containing future:
  [versions] constraint on future: 0.13.1
  Requirement of collective.documentgenerator: future>=0.14.0
  Requirement of z3c.table: future>=0.14.0
While:
  Installing instance.
Error: The requirement ('future>=0.14.0') is not allowed by your [versions] constraint (0.13.1)

**Comment by odelaere** [comment]
Hi @zhou0,

Future must be at least 0.14.0 for z3c.table and we rely on it in documentgenerator. 
So it would be quite difficult to support the version of future pinned in plone 4.3.19.

Since it's a [Python 2/3 compatibility library](https://python-future.org/) I think the most recent version is best to be used.
